import { mkdir, writeFile } from 'node:fs/promises';
import { createHash } from 'node:crypto';
const root = new URL('../', import.meta.url);
const sources = {
  elements: 'https://ssd.jpl.nasa.gov/sats/elem/',
  physical: 'https://ssd.jpl.nasa.gov/sats/phys_par/',
  discovery: 'https://ssd.jpl.nasa.gov/sats/discovery.html',
  constants: 'https://naif.jpl.nasa.gov/pub/naif/generic_kernels/pck/pck00011.tpc',
};
async function download(url) {
  const response = await fetch(url, { signal: AbortSignal.timeout(60000) });
  if (!response.ok) throw new Error(`${response.status}: ${url}`);
  return response.text();
}
const clean = value => value.replace(/<[^>]*>/g, '').replace(/&nbsp;|&#160;/g, ' ').replace(/&amp;/g, '&').replace(/\s+/g, ' ').trim();
const rows = html => [...html.matchAll(/<tr\b[^>]*>([\s\S]*?)<\/tr>/g)].map(match => match[1].split(/<td\b[^>]*>/).slice(1).map(cell => clean(cell.split('</td>')[0])));
const number = value => value !== '' && Number.isFinite(Number(value)) ? Number(value) : null;
const pages = {};
for (const [key, url] of Object.entries(sources)) pages[key] = await download(url);
const physical = new Map(rows(pages.physical).filter(row => /^\d+$/.test(row[2])).map(row => [Number(row[2]), { gm: number(row[3]), gmUncertainty: number(row[4]), radius: number(row[6]), radiusUncertainty: number(row[7]), density: number(row[9]) }]));
const satellites = rows(pages.elements).filter(row => row.length === 20 && /^\d+$/.test(row[3])).map(row => ({
  parent: row[1].toLowerCase(), name: row[2], code: Number(row[3]), solution: row[4], frame: row[5], epoch: row[6],
  aKm: Number(row[7]), e: Number(row[8]), w: Number(row[9]), ma0: Number(row[10]), i: Number(row[11]), om: Number(row[12]), periodDays: Number(row[13]),
  apsisYears: number(row[14]), nodeYears: number(row[15]), poleRA: number(row[16]), poleDec: number(row[17]),
  gm:null, radius:null, density:null, ...physical.get(Number(row[3])),
}));
if (satellites.length < 300 || satellites.some(row => !Number.isFinite(row.aKm) || !(row.periodDays > 0))) throw new Error('JPL orbital table format changed.');
let parent = '';
const discoveries = [];
for (const row of rows(pages.discovery)) {
  if (row.length === 1 && row[0].startsWith('Satellites of')) parent = row[0].match(/Satellites of\s+(\w+)/)[1].toLowerCase();
  if(parent==='dwarf') parent='pluto';
  else if (row.length === 6 && parent) discoveries.push({ parent, name: row[1] || row[2], designation: row[2], year: row[3], reference: row[5] });
}
const constants = {};
for (const match of pages.constants.matchAll(/BODY(\d+)_(RADII|POLE_RA|POLE_DEC|PM)\s*=\s*\(([^)]+)\)/g)) {
  const values = match[3].trim().split(/\s+/).map(value => Number(value.replace(/D/i, 'e')));
  if (values.every(Number.isFinite)) (constants[match[1]] ??= {})[match[2]] = values;
}
const result = { verifiedOn: new Date().toISOString().slice(0,10), sources, hashes: Object.fromEntries(Object.entries(pages).map(([key, value]) => [key, createHash('sha256').update(value).digest('hex')])), satellites, discoveries, constants };
await mkdir(new URL('src/astronomy/generated/', root), { recursive: true });
await writeFile(new URL('src/astronomy/generated/jplCatalog.ts', root), `// Generated by scripts/refresh-science.mjs from official JPL tables.\nexport const JPL_CATALOG = ${JSON.stringify(result)};\n`);
console.log(`Imported ${satellites.length} orbit records and ${discoveries.length} discovery records.`);
